### ISSUE TITLE
settings.py not in repo

### ISSUE THREAD

**Issue by joren485** [thaliawww/what-are-we-eating-today#2]
The following line results in an error:
```
from settings import SLACK_MAPPING
```

Because there is no `settings.py`.

**Comment by pingiun** [comment]
settings.py should be supplied in the deployment, it includes the mapping of wbw nicknames to slack full names. It is not included as it's specific to the deployment

**Comment by joren485** [comment]
An example `settings.py` would be nice.

**Comment by pingiun** [comment]
Go ahead, get some hacktober points
