### ISSUE TITLE
Integrate payment sharing

### ISSUE THREAD

**Issue by pingiun** [thaliawww/what-are-we-eating-today#46]
For food options that share the price among all eaters, implement functionality that let's someone pay and have the payments split evenly on wiebetaaltwat.nl

## Suggested implementation

If you want to join for e.g. lotus, react to the decision message with a 🐝. We need to think about how the final payment is entered in the system.

**Comment by joren485** [comment]
The simplest solution to this would be to add something like "Add :bee: to this message if you will join" to the slack message that decides what we will eat that day. The person who is paying can than easily add those people to the WieBetaaltWat themself.
